version: '3.7'

services:
  db:
    image: postgres:15
    container_name: booking_db
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432
  
  redis:
    image: redis:7
    container_name: booking_redis

  booking:
    build: .
    container_name: booking_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: ["/booking/docker/app.sh"]
    ports:
      - 7777:8000

  celery:
    build: .
    container_name: booking_celery
    command: ["/booking/docker/celery.sh", "celery"]
    env_file:
      - .env-non-dev
    depends_on:
      - redis

  flower:
    build: .
    container_name: booking_flower
    command: ["/booking/docker/celery.sh", "flower"]
    env_file:
      - .env-non-dev
    depends_on:
      - redis


      






    


    

